// Trending Hollywood + Bollywood content for Netflix-style demo UI
// Images are theme-matched stock photos (via loremflickr.com, keyed to each
// title's subject/genre), sized 2:3 like Netflix cards. Real movie/show
// posters are copyrighted — swap `image` for TMDB poster URLs
// (https://image.tmdb.org/t/p/w300/{poster_path}) once you have API access.

const data = [
  // ---------- Hollywood ----------
  {
    id: 1,
    title: "Jaws",
    description: "A giant great white shark terrorizes a New England beach town, forcing the police chief to hunt it down.",
    image: "https://loremflickr.com/300/450/shark,ocean",
    genre: "Thriller",
    industry: "Hollywood",
    isShow: false,
    rated: "PG",
    imdbRating: 8.1,
    year: 1975,
    duration: "2h 04m",
    addedDate: "2026-09-01",
  },
  {
    id: 2,
    title: "Alien",
    description: "The crew of a commercial spacecraft encounters a deadly extraterrestrial creature after investigating a distress signal.",
    image: "https://loremflickr.com/300/450/alien,spaceship",
    genre: "Sci-Fi",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 8.5,
    year: 1979,
    duration: "1h 57m",
    addedDate: "2026-09-01",
  },
  {
    id: 3,
    title: "Scarface",
    description: "A Cuban refugee rises to the top of Miami's ruthless drug trade in this violent crime saga.",
    image: "https://loremflickr.com/300/450/miami,city",
    genre: "Crime",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 8.3,
    year: 1983,
    duration: "2h 50m",
    addedDate: "2026-09-01",
  },
  {
    id: 4,
    title: "Ready or Not",
    description: "A bride's wedding night takes a deadly turn when her new in-laws force her into a lethal game of hide-and-seek.",
    image: "https://loremflickr.com/300/450/mansion,wedding",
    genre: "Horror",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 6.9,
    year: 2019,
    duration: "1h 35m",
    addedDate: "2026-09-01",
  },
  {
    id: 5,
    title: "Smile 2",
    description: "A pop superstar begins experiencing terrifying, inexplicable events days before her world tour.",
    image: "https://loremflickr.com/300/450/concert,popstar",
    genre: "Horror",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 6.8,
    year: 2024,
    duration: "2h 07m",
    addedDate: "2026-09-01",
  },
  {
    id: 6,
    title: "Conan the Barbarian",
    description: "A warrior sets out on a path of revenge after the slaughter of his tribe by a savage warlord.",
    image: "https://loremflickr.com/300/450/warrior,sword",
    genre: "Action",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 6.9,
    year: 1982,
    duration: "2h 09m",
    addedDate: "2026-09-01",
  },
  {
    id: 7,
    title: "The Gentlemen",
    description: "An aristocratic Englishman finds himself embroiled in the murky world of London's criminal underworld.",
    image: "https://loremflickr.com/300/450/london,suit",
    genre: "Crime",
    industry: "Hollywood",
    isShow: true,
    rated: "TV-MA",
    imdbRating: 7.8,
    year: 2026,
    duration: "Season 2",
    addedDate: "2026-09-03",
  },
  {
    id: 8,
    title: "Stranger Things: Tales From '85",
    description: "A companion special expanding on the world and mysteries of Hawkins, Indiana.",
    image: "https://loremflickr.com/300/450/arcade,retro",
    genre: "Sci-Fi",
    industry: "Hollywood",
    isShow: true,
    rated: "TV-14",
    imdbRating: 7.5,
    year: 2026,
    duration: "Limited Series",
    addedDate: "2026-09-01",
  },
  {
    id: 9,
    title: "Monster: The Lizzie Borden Story",
    description: "Ryan Murphy's true-crime anthology turns to the infamous 1892 double murder case that gripped America.",
    image: "https://loremflickr.com/300/450/courtroom,axe",
    genre: "Crime Drama",
    industry: "Hollywood",
    isShow: true,
    rated: "TV-MA",
    imdbRating: 7.2,
    year: 2026,
    duration: "1 Season",
    addedDate: "2026-09-01",
  },
  {
    id: 10,
    title: "Straight Outta Compton",
    description: "The rise and fall of the seminal gangsta rap group N.W.A and its members' impact on music and culture.",
    image: "https://loremflickr.com/300/450/hiphop,microphone",
    genre: "Biography",
    industry: "Hollywood",
    isShow: false,
    rated: "R",
    imdbRating: 7.8,
    year: 2015,
    duration: "2h 27m",
    addedDate: "2026-09-01",
  },

  // ---------- Bollywood ----------
  {
    id: 11,
    title: "Gandhari",
    description: "A mother who loses her eyesight and her daughter to a kidnapping ring fights to uncover the truth.",
    image: "https://loremflickr.com/300/450/india,mother",
    genre: "Thriller",
    industry: "Bollywood",
    isShow: false,
    rated: "UA",
    imdbRating: 7.0,
    year: 2026,
    duration: "2h 08m",
    addedDate: "2026-09-03",
  },
  {
    id: 12,
    title: "Mirzapur: The Movie",
    description: "The battle for control of Mirzapur reaches its climax as Guddu Pandit and Kaleen Bhaiya face off for the throne.",
    image: "https://loremflickr.com/300/450/gangster,india",
    genre: "Crime",
    industry: "Bollywood",
    isShow: false,
    rated: "A",
    imdbRating: 8.2,
    year: 2026,
    duration: "2h 20m",
    addedDate: "2026-09-05",
  },
  {
    id: 13,
    title: "Dhamaal 4",
    description: "A new treasure hunt sends a chaotic group of friends chasing riches across the country in this comedy sequel.",
    image: "https://loremflickr.com/300/450/treasure,comedy",
    genre: "Comedy",
    industry: "Bollywood",
    isShow: false,
    rated: "UA",
    imdbRating: 6.1,
    year: 2026,
    duration: "2h 15m",
    addedDate: "2026-09-01",
  },
  {
    id: 14,
    title: "Border 2",
    description: "A new generation of soldiers faces an intense battle on the frontlines in this patriotic war drama sequel.",
    image: "https://loremflickr.com/300/450/soldier,army",
    genre: "War",
    industry: "Bollywood",
    isShow: false,
    rated: "UA",
    imdbRating: 7.3,
    year: 2026,
    duration: "2h 34m",
    addedDate: "2026-01-23",
  },
  {
    id: 15,
    title: "Panchayat",
    description: "An engineering graduate takes a reluctant job as secretary of a remote village panchayat office in Uttar Pradesh.",
    image: "https://loremflickr.com/300/450/village,india",
    genre: "Comedy Drama",
    industry: "Bollywood",
    isShow: true,
    rated: "U",
    imdbRating: 8.9,
    year: 2026,
    duration: "Season 5",
    addedDate: "2026-08-15",
  },
  {
    id: 16,
    title: "Gandhi",
    description: "A historical drama following Mahatma Gandhi's early life from 1888 to 1915, including his years in London and South Africa.",
    image: "https://loremflickr.com/300/450/gandhi,history",
    genre: "Historical Drama",
    industry: "Bollywood",
    isShow: true,
    rated: "U/A 13+",
    imdbRating: 8.0,
    year: 2026,
    duration: "1 Season",
    addedDate: "2026-09-17",
  },
  {
    id: 17,
    title: "The Revolutionaries",
    description: "Four young rebels turn to armed resistance in their fight against British rule during India's freedom struggle.",
    image: "https://loremflickr.com/300/450/revolution,india",
    genre: "Historical Drama",
    industry: "Bollywood",
    isShow: true,
    rated: "U/A 16+",
    imdbRating: 7.6,
    year: 2026,
    duration: "1 Season",
    addedDate: "2026-09-04",
  },
  {
    id: 18,
    title: "Gullak",
    description: "The Mishra family's everyday joys and struggles unfold with warmth and humor in a small-town Indian household.",
    image: "https://loremflickr.com/300/450/family,india",
    genre: "Slice of Life",
    industry: "Bollywood",
    isShow: true,
    rated: "U",
    imdbRating: 8.7,
    year: 2026,
    duration: "Season 5",
    addedDate: "2026-07-10",
  },
  {
    id: 19,
    title: "Gram Chikitsalay",
    description: "A newly graduated doctor clashes with a corrupt official while struggling to run a rural village health center.",
    image: "https://loremflickr.com/300/450/clinic,doctor",
    genre: "Comedy Drama",
    industry: "Bollywood",
    isShow: true,
    rated: "U/A 13+",
    imdbRating: 7.9,
    year: 2026,
    duration: "Season 2",
    addedDate: "2026-06-23",
  },
  {
    id: 20,
    title: "Bigg Boss 20",
    description: "Contestants from all walks of life live under constant surveillance in India's biggest reality TV house.",
    image: "https://loremflickr.com/300/450/television,studio",
    genre: "Reality",
    industry: "Bollywood",
    isShow: true,
    rated: "U/A 16+",
    imdbRating: 4.2,
    year: 2026,
    duration: "Season 20",
    addedDate: "2026-09-01",
  },
];

export default data;